server:
  port: 9000

spring:
  application:
    name: plum
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
  devtools:
    livereload:
      port: 35732

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: on

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: on
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

sa-token:
  sso:
    ticket-timeout: 300
    allow-url: *
    is-slo: true
    isHttp: true

info:
  app:
    name: ${spring.application.name}
    version: @project.version@
  owner:
    name: 李井田
    email: ljngtan@qq.com