server:
  port: 18080

spring:
  application:
    name: peanut
  datasource:
    url: jdbc:mysql://localhost:3306/peanut
    username: root
    password: 123456
  devtools:
    livereload:
      port: 35734
  jpa:
    open-in-view: on
    show-sql: on
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: on

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: on
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

sa-token:
  sso:
    auth-url: http://localhost:9000/sso/auth
    is-slo: true
    is-http: true
    check-ticket-url: http://localhost:9000/sso/checkTicket

sip:
  stack-name: 34010300002000000001

logging:
  level:
    com.plant.fruit.peanut.sip: debug

info:
  app:
    name: ${spring.application.name}
    version: @project.version@
  owner:
    name: 李井田
    email: ljngtan@qq.com