server:
  port: 18081

spring:
  application:
    name: olive
  datasource:
    url: jdbc:mysql://localhost:3306/olive
    username: root
    password: 123456
  devtools:
    livereload:
      port: 35735
  jpa:
    open-in-view: on
    show-sql: on
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: on

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: on
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: ${spring.application.name}
    version: @project.version@
  owner:
    name: 李井田
    email: ljngtan@qq.com