server:
  port: 18079

spring:
  application:
    name: pineapple
  datasource:
    url: jdbc:mysql://localhost:3306/pineapple
    username: root
    password: 123456
  devtools:
    livereload:
      port: 35733
  jpa:
    open-in-view: on
    show-sql: on

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: on

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: on
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

sa-token:
  sso:
    auth-url: http://localhost:9000/sso/auth
    is-slo: true
    is-http: true
    check-ticket-url: http://localhost:9000/sso/checkTicket

info:
  app:
    name: ${spring.application.name}
    version: @project.version@
  owner:
    name: 李井田
    email: ljngtan@qq.com