server:
  port: 8040

spring:
  application:
    name: strawberry
  cloud:
    gateway:
      discovery:
        locator:
          enabled: on
          lower-case-service-id: on
      routes:
        - id: plum
          uri: lb://plum
          predicates:
            - Path=/sso/**
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
  devtools:
    livereload:
      port: 35731

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: on

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: on
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

sa-token:
  filter:
    includes:
      - /**
    excludes:
      - /favicon.ico

info:
  app:
    name: ${spring.application.name}
    version: @project.version@
  owner:
    name: 李井田
    email: ljngtan@qq.com